### ISSUE TITLE
can't display images from media folder

### ISSUE THREAD

**Issue by InesSehili** [creativetimofficial/material-dashboard-django#2]
hi
i am using this template for my project, when i tried Media folder form  uploading images it works for me but i cannot displaying images in my templates. all my configuration are correct please help me !!!

**Comment by app-generator** [comment]
Hello @InesSehili 

Thank you for using our products.
To see a correct configuration regarding the display of an uploaded image please take a look at this open-source sample: 

- [Django User Profile](https://github.com/app-generator/django-user-profile)

Relevant files/folders:
- Project [Settings](https://github.com/app-generator/django-user-profile/blob/master/core/settings.py)
- [Customers App](https://github.com/app-generator/django-user-profile/tree/master/customers) that manages the upload

Let us know your project

**Comment by InesSehili** [comment]
Hello
Thank you for your response. I copy the configuration from
django-user-profile to material-dashboard-django-master and the problem
remains the same after trying all the solutions and possible
configurations. I'm
going to swing to django-user-profile the media folder works fine for me
and I have to redo everything but the essentials c that it works. Thanks
for your efforts. Ines SEHILI

Le dim. 23 mai 2021 à 05:00, App Generator ***@***.***> a
écrit :

**Comment by app-generator** [comment]
This `use-case` is scheduled to be documented soon in the product docs, blog, or `knowledge-center`. 
We will announce it in the community once the content is published. 

Thanks again for using our [Django Templates](https://www.creative-tim.com/templates/django).

**Comment by InesSehili** [comment]
You are welcome

Le dim. 23 mai 2021 à 12:02, App Generator ***@***.***> a
écrit :
