### ISSUE TITLE
selectpicker dropdown not working

### ISSUE THREAD

**Issue by prabhatsingh2011** [creativetimofficial/material-dashboard-django#3]
Hi Team,

Thank you for making such a great product. I am having issues rendering selectpicker in form. Please help. I  have reproduced the issue in default login page also.

![image](https://user-images.githubusercontent.com/8909629/119252869-25648800-bbcc-11eb-818b-0e53553f339d.png)

On clicking button nothing is coming up.

![image](https://user-images.githubusercontent.com/8909629/119252893-3ca37580-bbcc-11eb-8b13-ac90fd85a3f0.png)

This is what i have put in login form. 

<div class="row">
              <div class="col-md-12">
            
             <select multiple class="form-control selectpicker" data-style="btn btn-link" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
</div>
</div>

**Comment by app-generator** [comment]
Hello @prabhatsingh2011, 

Thank you for using our products. 
Just made a quit test and the result can be found on this [CodePen](https://codepen.io/app-generator/pen/ExWWrpm)

**Set up**
- Added required CSS `bootstrap-select.min.css` - CDN version
- Added JS `bootstrap-select.min.js` - CDN version
- Added Select control 

```html
<select class="selectpicker">
    <option>Mustard</option>
    <option>Ketchup</option>
    <option>Barbecue</option>
</select>
``` 

**Layout**

![image](https://user-images.githubusercontent.com/51070104/119256916-aa9b6d00-bbcb-11eb-9c96-b2c3dead064e.png)

**Expended view**

![image](https://user-images.githubusercontent.com/51070104/119256947-cdc61c80-bbcb-11eb-9182-ca02923d0b27.png)

---

From this point try to use inline styling until you get closer to a better version. 
Let us know your progress.

**Comment by prabhatsingh2011** [comment]
It is working. Thank you so much!!

**Comment by app-generator** [comment]
Glad it worked @prabhatsingh2011, 

Thanks for using our [Django Templates](https://www.creative-tim.com/templates/django).
