### ISSUE TITLE
noUiSliders not showing & buggy

### ISSUE THREAD

**Issue by jacksund** [creativetimofficial/material-dashboard-django#5]
Hey everyone,

I'm struggling to get the sliders to show when using this django template. When I inspect the html, there aren't any errors and the slider looks to be there... it's just not visible in the UI.

Is this being disabled as a pro feature? Or would there be some other reason the sliders are being hidden? 

On a similar note, the [documentation for the slider](https://demos.creative-tim.com/material-dashboard-django/docs/1.0/plugins/sliders.html) also looks to be broken.

**Comment by app-generator** [comment]
Hello @jacksund, 

Thank you for using our products. 
The slider component is available in the PRO version ( Forms -> Extended Forms Page). 

Let us know if you need further assistance. 

P.S. The product will be updated in the coming hours.
